Repository SolidoLeague/todo, pull requests merged in 2018-07, with the labels that each got.

#1 Updating index.html and index.css
  index.css
  index.html
  index.js
Labels: enhancement

#2 Add append method to result-field
  index.css
  index.html
  index.js
Labels: enhancement

#4 Todocolors branch: change colors of todos based on priorities
  index.js
Labels: bug, enhancement

#5 Todo app
  index.css
  index.html
  index.js
Labels: enhancement

#8 Create README for project description
  README.md
Labels: enhancement

#9 fixing date display
  index.css
  index.js
Labels: enhancement

#10 Add method for deleting list
  index.js
Labels: enhancement

#11 Refactor almost all business logic & process
  README.md
  index.css
  index.html
  index.js
Labels: bug, enhancement, help wanted
